version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: today
      WORDPRESS_DB_PASSWORD: today
      WORDPRESS_DB_NAME: prototoday
    volumes:
      - type: bind
        source: ./www
        target: /var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: prototoday
      MYSQL_USER: today
      MYSQL_PASSWORD: today
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
